travis:
  secure:
    BINSTAR_TOKEN: LQ3+lVSswtPmXVuK00oK+B26Vd0xtk3qLy26zRNrLsvlGSWQzAfs9Hg91EqaWkPXv6u+OavPUp19/KKxa48ABKZqZxJhmG8h36v8fVhLy6snmyfkuVv+vpSlDUzTo+OvkaTgqGgeX0WqBGH0Yr9aahg0QBzQ0NxyHMwUxi9ZUxcYeVjRy2Rdrp8rXh/6YFOXHqCpXpy7670nsMIoWUVaa2YsqnkJMyPk0PvQWa37dQ+1UuoUPVob2/oJBdzt0xF9BuKxVoxlnzqZsbD2ydD/LuRqI3TV6TQkqkNK/3pSCzlbApv5Ejqwu0OM9Fq3CHbsZAuhQDvPt6xssAxjQLduR9q10vf5t5tA6vH2LnUPyMkx+TPVaaZxxZBP5WV3QHXebhOQc79PZXit/0g+Ff22q5EYfaO2LOYfA0o+mS5eKqMrwvEUut/sp9zlQ9Qpke4eBxEUX9VRwuHBU4ZyEgEpf6I+8tBmOOaHD082Tq9BceuGZXP22GsNRRGehWQQIAF+4M2j3MAjnt/gthIXtIrnlC4GraHiy9nSqueqyascs5Seafzqd2aY+eap5Et350Ls+GpSN9acR/KZPqPLkq3gGYYRAfM2qzZHQBFzikShscC4rDWprrCVWveXwYlMxlcK8si4EeT05+WHTAQkkzszYM6Tr0nvsG3L1Fu/yqPlJjQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
